export enum MessageType {
  MSG_EXTRACT_SNAPSHOT = 'MSG_EXTRACT_SNAPSHOT',
  MSG_EXTRACT_SNAPSHOT_SUCCESS = 'MSG_EXTRACT_SNAPSHOT_SUCCESS',
  MSG_EXTRACT_SNAPSHOT_ERROR = 'MSG_EXTRACT_SNAPSHOT_ERROR',
  MSG_EXTRACT_SNAPSHOT_PROCESSING = 'MSG_EXTRACT_SNAPSHOT_PROCESSING',

  MSG_SEND_SNAPSHOT_EXTRACTION_SUCCESS = 'MSG_SEND_SNAPSHOT_EXTRACTION_SUCCESS',
  MSG_SEND_SNAPSHOT_EXTRACTION_ERROR = 'MSG_SEND_SNAPSHOT_EXTRACTION_ERROR',
}
