export enum VideoImageExtractionStatus {
  VIDEO_IMAGE_EXTRACTION_REQUESTED = 'VIDEO_IMAGE_EXTRACTION_REQUESTED',
  VIDEO_IMAGE_EXTRACTION_PENDING = 'VIDEO_IMAGE_EXTRACTION_PENDING',
  VIDEO_IMAGE_EXTRACTION_PROCESSING = 'VIDEO_IMAGE_EXTRACTION_PROCESSING',
  VIDEO_IMAGE_EXTRACTION_SUCCESS = 'VIDEO_IMAGE_EXTRACTION_SUCCESS',
  VIDEO_IMAGE_EXTRACTION_ERROR = 'VIDEO_IMAGE_EXTRACTION_ERROR',
}
